name: "Publish and Annotate"
description: "Publish the project, capture logs, and annotate warnings and errors."

inputs:
  app-dir:
    description: "Directory of the application project"
    required: true
  app:
    description: "Name of the application project"
    required: true
  version-container:
    description: "Version for the container"
    required: true

runs:
  using: composite
  steps:
    - name: Create Log Directory
      run: mkdir -p "${{ inputs.app-dir }}/logs"

    - name: Publish the project and capture logs
      shell: bash
      run: dotnet publish "${{ inputs.app-dir }}/${{ inputs.app }}.csproj" -c Release -o ./dotnet_publish -p:Version="${{ inputs.version-container }}" > "${{ inputs.app-dir }}/logs/publish.log" 2>&1 || true

    - name: Annotate .NET Publish log
      shell: bash
      run: |
        grep "warning" "${{ inputs.app-dir }}/logs/publish.log" | while read -r line; do
          echo "::warning title=.NET Publish::$line"
        done || true
        grep "error" "${{ inputs.app-dir }}/logs/publish.log" | while read -r line; do
          echo "::error title=.NET Publish::$line"
        done || true
