name: "Test and Annotate"
description: "Run tests, capture logs, and annotate warnings and errors."

inputs:
  test-dir:
    description: "Directory of the test project"
    required: true
  test-library:
    description: "Name of the test project library"
    required: true

runs:
  using: composite
  steps:
    - name: Test the project and capture logs
      shell: bash
      run: dotnet test -c Release --verbosity normal "${{ inputs.test-dir }}/${{ inputs.test-library }}.csproj" > "${{ inputs.test-dir }}/${{ inputs.test-library }}-test.log" 2>&1 || true

    - name: Annotate .NET Test log
      shell: bash
      run: |
        grep "warning" "${{ inputs.test-dir }}/${{ inputs.test-library }}-test.log" | while read -r line; do
          echo "::warning title=.NET Test::$line"
        done || true
        grep "error" "${{ inputs.test-dir }}/${{ inputs.test-library }}-test.log" | while read -r line; do
          echo "::error title=.NET Test::$line"
        done || true
