name: Build, Test, and Publish .NET Core and React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build and Capture Logs for WebApiServer
      run: dotnet build --no-incremental -warnaserror WebApiServer/WebApiServer.csproj > webapi_build.log 2>&1 || true

    - name: Annotate WebApiServer Build Logs
      run: |
        # .NET build logs
        grep "warning" webapi_build.log | while read -r line; do
          echo "::warning title=.NET Lint::$line"
        done || true

        grep "error" webapi_build.log | while read -r line; do
          echo "::error title=.NET Lint::$line"
        done || true
        
    - name: Annotate WebApiServer Build Logs
      run: |
        # NPM build logs
        if [ -f WebApiServer/clientapp/npm_build.log ]; then
          grep -i "warning" WebApiServer/clientapp/npm_build.log | while read -r line; do
            echo "::warning title=React Build::$line"
          done || true

          grep -i "error" WebApiServer/clientapp/npm_build.log | while read -r line; do
            echo "::error title=React Build::$line"
          done || true
        fi

    - name: Test the project and capture logs
      run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true

    - name: Annotate Test Logs
      run: |
        grep "warning" test.log | while read -r line; do
          echo "::warning title=.NET Test::$line"
        done || true

        grep "error" test.log | while read -r line; do
          echo "::error title=.NET Test::$line"
        done || true

    - name: Publish the project and capture logs
      run: dotnet publish WebApiServer/WebApiServer.csproj -c Release -o ./dotnet_publish -p:Version="${{ github.sha }}" > publish.log 2>&1 || true

    - name: Annotate .NET Publish Logs
      run: |
        grep "warning" publish.log | while read -r line; do
          echo "::warning:.NET Publish Warning:$line"
        done || true
    
        grep "error" publish.log | while read -r line; do
          echo "::error:.NET Publish Error:$line"
        done || true

