name: Build, Test, and Publish .NET Core and React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build and Capture Logs for WebApiServer
      run: dotnet build --no-incremental -warnaserror WebApiServer/WebApiServer.csproj > webapi_build.log 2>&1 || true

    - name: .NET Lint Log
      run: |
        # .NET build logs
        grep "warning" ./webapi_build.log | while read -r line; do
          echo "::warning title=.NET Lint::$line"
        done
        grep "error" ./webapi_build.log | while read -r line; do
          echo "::error title=.NET Lint::$line"
        done || true
    - name: Install dependencies for React
      run: npm install
      working-directory: ./clientapp

    - name: Run npm lint
      run: |
        cd clientapp
        npm run lint > npm_lint.log 2>&1 || true
    - name: Annotate npm lint warnings and errors
      run: |
        # Annotate warnings from npm lint
        grep -i 'warning' clientapp/npm_lint.log | while read -r line; do
          echo "::warning title=NPM Lint::$line"
        done
        # Annotate errors from npm lint
        grep -i 'error' clientapp/npm_lint.log | while read -r line; do
          echo "::error title=NPM Lint::$line"
        done
        
    - name: Display npm lint logs
      run: |
        echo "==== NPM LINT LOG ===="
        cat clientapp/npm_lint.log
        
    - name: Build npm package and capture logs
      id: npm-build
      run: |
        echo "Starting npm build..."
        npm run build > npm_build.log 2>&1 || true
      working-directory: ./clientapp
      continue-on-error: true

    - name: Test the project and capture logs
      run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true

    - name: Annotate .NET Test log
      run: |
        grep "warning" test.log | while read -r line; do
          echo "::warning title=.NET Test::$line"
        done || true
        grep "error" test.log | while read -r line; do
          echo "::error title=.NET Test::$line"
        done || true
    - name: Publish the project and capture logs
      run: dotnet publish WebApiServer/WebApiServer.csproj -c Release -o ./dotnet_publish -p:Version="${{ github.sha }}" > publish.log 2>&1 || true

    - name: Annotate .NET Publish log
      run: |
        grep "warning" publish.log | while read -r line; do
          echo "::warning::$line"
        done
    
        grep "error" publish.log | while read -r line; do
          echo "::error::$line"
        done || true

    - name: Annotate npm run log
      run: |
        # npm build warnings
        grep -i "warning" clientapp/npm_build.log | while read -r line; do
          echo "::warning file=${{ github.workspace }}/clientapp/npm-build.log::$line"
        done
        # npm build errors
        grep -i "error" clientapp/npm_build.log | while read -r line; do
          echo "::error file=${{ github.workspace }}/clientapp/npm_build.log::$line"
        done || true
