name: Build, Test, and Publish .NET Core and React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js environment for React app
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # 3. Setup .NET SDK environment for WebApiServer
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    # 4. Build .NET project and capture logs for WebApiServer
    - name: Build and Capture Logs for WebApiServer
      run: dotnet build --no-incremental -warnaserror WebApiServer/WebApiServer.csproj > webapi_build.log 2>&1 || true

    # 5. Annotate .NET Lint logs
    - name: .NET Lint Log
      run: |
        grep "warning" ./webapi_build.log | while read -r line; do
          echo "::warning title=.NET Lint::$line"
        done || true
        grep "error" ./webapi_build.log | while read -r line; do
          echo "::error title=.NET Lint::$line"
        done || true

    # 6. Install dependencies for React
    - name: Install dependencies for React
      run: npm install
      working-directory: ./clientapp

    # 7. Run npm lint and capture logs
    - name: Run npm lint
      run: |
        cd clientapp
        npm run lint > npm_lint.log 2>&1 || true

    # 8. Annotate npm lint warnings and errors
    - name: Annotate npm lint warnings and errors
      run: |
        # Annotate warnings from npm lint
        grep -i 'warning' clientapp/npm_lint.log | while read -r line; do
          echo "::warning title=NPM Lint::$line"
        done || true
        # Annotate errors from npm lint
        grep -i 'error' clientapp/npm_lint.log | while read -r line; do
          echo "::error title=NPM Lint::$line"
        done || true

    # 9. Display npm lint logs
    - name: Display npm lint logs
      run: |
        echo "==== NPM LINT LOG ===="
        cat clientapp/npm_lint.log

    # 10. Build npm package and capture logs (continue on error)
    - name: Build npm package and capture logs
      id: npm-build
      run: |
        echo "Starting npm build..."
        npm run build > npm_build.log 2>&1 || true
      working-directory: ./clientapp
      continue-on-error: true

    # 11. Run .NET tests and capture logs
    - name: Test the project and capture logs
      run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true

    # 12. Annotate .NET Test logs
    - name: Annotate .NET Test log
      run: |
        grep "warning" test.log | while read -r line; do
          echo "::warning title=.NET Test::$line"
        done || true
        grep "error" test.log | while read -r line; do
          echo "::error title=.NET Test::$line"
        done || true

    # 13. Publish .NET project and capture logs
    - name: Publish the project and capture logs
      run: dotnet publish WebApiServer/WebApiServer.csproj -c Release -o ./dotnet_publish -p:Version="${{ github.sha }}" > publish.log 2>&1 || true

    # 14. Annotate .NET Publish logs
    - name: Annotate .NET Publish log
      run: |
        grep "warning" publish.log | while read -r line; do
          echo "::warning::$line"
        done || true
        grep "error" publish.log | while read -r line; do
          echo "::error::$line"
        done || true

    # 15. Annotate npm build logs
    - name: Annotate npm build log
      run: |
        # npm build warnings
        grep -i "warning" clientapp/npm_build.log | while read -r line; do
          echo "::warning file=${{ github.workspace }}/clientapp/npm-build.log::$line"
        done || true
        # npm build errors
        grep -i "error" clientapp/npm_build.log | while read -r line; do
          echo "::error file=${{ github.workspace }}/clientapp/npm_build.log::$line"
        done || true
