name: Build, Test, and Publish .NET Core and React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Build WebApiServer (includes npm build via .csproj)
    - name: Build WebApiServer
      run: dotnet build WebApiServer/WebApiServer.csproj --configuration Release

    # Annotate npm Build Logs (if errors/warnings are logged via csproj)
    - name: Annotate npm Build Logs
      run: |
        grep -i "warning" WebApiServer/clientapp/npm_build.log | while read -r line; do
          echo "::warning file=${{ github.workspace }}/WebApiServer/clientapp/npm_build.log::$line"
        done || true
